### ISSUE TITLE
Error client Nvidia

### ISSUE THREAD

**Issue by filo1992** [Etayson/BC_server-client#3]
crackhelperClientX64.exe -prog cuBitCrack.exe -name ciao -pass x -pool 192.168.99.65:8000 -t 256 -b 32 -p 1000
pause

crackhelperServerX64.exe -range 8000000000000000:ffffffffffffffff -dp 22 -map range.bin -address 16jY7qLJnxb7CHZyqBP8qca9d51gAjyXQN
pause

File map
https://drive.google.com/file/d/12feJRjsvOL5lVNK_98K4NN21kshhN6JG/view?usp=sharing
![Untitled](https://user-images.githubusercontent.com/8825601/89123985-ccf4ba80-d4d3-11ea-9735-121c8d62018c.png)

**Comment by Etayson** [comment]
You show different ranges in command line and in console.
In command line you show correct ranges multiple of 2 in console something different..
With range multiple of 2 you should have subranges multiple of 2 and beginning of keyspace should start with zeros at right part 
Becouse each subranges with dp 22 equil to 000001ffffffffff = 2^41
So subrange should be like this
804e1e0000000000:804e1fffffffffff
but you have something other.
